# VS Code REST Client requests
# Requires extension: humao.rest-client

@host = http://localhost:8080
@json = application/json
@uid = 04:A3:B2:11
@api-key = MY_SECRET_API_KEY

### Health check
GET {{host}}/health
Accept: {{json}}

### Get current attendees
GET {{host}}/current
Accept: {{json}}
Headers:
  x-api-key: {{api-key}}

### Get attendee count
GET {{host}}/count
Accept: {{json}}
Headers:
  x-api-key: {{api-key}}

### Get scan history (last 10 scans)
GET {{host}}/scan-history
Accept: {{json}}
Headers:
  x-api-key: {{api-key}}

### Get visits (attendance history)
GET {{host}}/visits
Accept: {{json}}
Headers:
  x-api-key: {{api-key}}

### Scan: sign in/out with UID
POST {{host}}/scan
Content-Type: {{json}}
Headers:
  x-api-key: {{api-key}}

{
  "uid": "{{uid}}"
}

### Sign out all attendees
POST {{host}}/sign-out-all
Content-Type: {{json}}
Headers:
  x-api-key: {{api-key}}

### Sign in with Discord ID
POST {{host}}/sign-in-discord
Content-Type: {{json}}
Headers:
  x-api-key: {{api-key}}

{
  "discord_id": "111111111"
}

### Sign out with Discord ID
POST {{host}}/sign-out-discord
Content-Type: {{json}}
Headers:
  x-api-key: {{api-key}}

{
  "discord_id": "111111111"
}

### Create a new member
POST {{host}}/members
Content-Type: {{json}}
Headers:
  x-api-key

{
  "name": "Charlie",
  "uid": "04:AA:BB:CC:DD",
  "discord_id": "333333333"
}

### List members
GET {{host}}/members
Accept: {{json}}
Headers:
  x-api-key: {{api-key}}

### Export members to JSON file
GET {{host}}/export-members
Accept: {{json}}
Headers:
  x-api-key: {{api-key}}

### Import members from JSON file
POST {{host}}/import-members
Content-Type: {{json}}
Headers:
  x-api-key: {{api-key}}